class FYImages {
  static const String logo = 'assets/images/logo.png';
  static const String appIcon_32 = 'assets/images/appIcon_32.png';
  static const String riskyBg = 'assets/images/risky_bg.png';
  static const String riskIcon = 'assets/images/risky_icon.png';
  static const String hotIcon = 'assets/images/hot_icon1.png';
  static const String aiIcon = 'assets/images/ai_icon.png';
  static const String orderIcon = 'assets/images/order_icon1.png';
  static const String settingIcon = 'assets/images/setting_icon.png';
  static const String detailList = 'assets/images/detail_list1.png';
  static const String login_bg = 'assets/images/login_bg.png';
  static const String login_account = 'assets/images/login_account.png';
  static const String login_pwd = 'assets/images/login_pwd.png';
  static const String pwd_see = 'assets/images/pwd_see.png';
  static const String pwd_unsee = 'assets/images/pwd_unsee.png';
  static const String image_1 = 'assets/images/image_1.png';
  static const String tip_icon = 'assets/images/tip.png';
  static const String icon_back = 'assets/images/icon_back.png';
  static const String download_icon = 'assets/images/download_icon.png';
  static const String history_icon = 'assets/images/history.png';
  static const String addAI = 'assets/images/add_ai.png';
  static const String addTip = 'assets/images/add_tip.png';
  static const String sendIcon = 'assets/images/send_icon.png';
  static const String aiTip = 'assets/images/ai_tip.png';
  static const String robot = 'assets/images/robot.png';
  static const String down_icon = 'assets/images/down_icon.png';
  static const String cancle_cion = 'assets/images/cancle_cion.png';
  static const String choose_icon = 'assets/images/choose_icon.png';
  static const String unchoose_icon = 'assets/images/unchoose_icon.png';
  static const String oder_share = 'assets/images/oder_share.png';
  static const String calendar = 'assets/images/calendar.png';
  static const String calendar_unchoose = 'assets/images/calendar_unchoose.png';
  static const String zhuanti_choose = 'assets/images/zhuanti_choose.png';
  static const String zhuanti_unchoose = 'assets/images/zhuanti_unchoose.png';
  static const String attention_unchoose = 'assets/images/attention_unchoose.png';
  static const String attention_choose = 'assets/images/attention_choose.png';
  static const String fileEarmarkMedical = 'assets/images/file-earmark-medical.png';
  static const String star = 'assets/images/star.png';
  static const String check_icon = 'assets/images/check_icon.png';
  static const String uncheck_icon = 'assets/images/uncheck_icon.png';
  static const String default_avatar = 'assets/images/default_avatar.png';
  static const String setting_person = 'assets/images/setting_person.png';
  static const String setting_phone = 'assets/images/setting_phone.png';
  static const String setting_message = 'assets/images/setting_message.png';
  static const String setting_data = 'assets/images/setting_data.png';
  static const String setting_permission = 'assets/images/setting_permisson.png';
  static const String setting_tongji = 'assets/images/setting_tongji.png';
  static const String user_avatar = 'assets/images/user_avatar.png';
  static const String privacy_safe = 'assets/images/privacy_safe.png';
  static const String search_icon = 'assets/images/search_icon.png';
  static const String calendar_black = 'assets/images/calendar_black.png';
  static const String lunbo1 = 'assets/images/lunbo1.png';
  static const String lunbo2 = 'assets/images/lunbo2.png';
  static const String lunbo3 = 'assets/images/lunbo3.png';
  static const String report_icon = 'assets/images/report_icon.png';
  static const String blank_page = 'assets/images/blank_page.png';
  static const String add_tip_mock = 'assets/images/add_tip_mock.png';
  static const String my_mock = 'assets/images/my_mock.png';
  static const String messenge_icon = 'assets/images/messenge_icon.png';
  static const String cancel_red = 'assets/images/cancel_red.png';
  static const String userSetting_icon = 'assets/images/userSetting_icon.png';
  static const String refuse_red = 'assets/images/refuse_red.png';
  static const String check_gree = 'assets/images/check_gree.png';
  static const String uncheck = 'assets/images/uncheck.png';
  static const String open_icon = 'assets/images/open_icon.png';
  static const String unopen_icon = 'assets/images/unopen_icon.png';
  static const String more_info = 'assets/images/more_info.png';
  static const String start_use = 'assets/images/start_use.png';
  static const String event_tutorial = 'assets/images/event_tutorial.png';
  static const String analyse_tutorial = 'assets/images/analyse_tutorial.png';
  static const String tutorial_feedBack = 'assets/images/tutorial_feedBack.png';
  static const String export_data = 'assets/images/export_data.png'; // 数据导出
  static const String bannerLoad = 'assets/loadImage.png'; // 轮播图占位图
  static const String hotIsRead = 'assets/images/hot_isRead.png'; // 舆情热点已读
  static const String hot1 = 'assets/images/hot1.png'; // 舆情热点1
  static const String hot2 = 'assets/images/hot2.png'; // 舆情热点2
  static const String hot3 = 'assets/images/hot3.png'; // 舆情热点3
  static const String hot4 = 'assets/images/hot4.png'; // 舆情热点4
  static const String hot5 = 'assets/images/hot5.png'; // 舆情热点5
}